<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHdrHasl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHdrHasl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHdrHasl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHdrHasl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHdrHasl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HdrHasl',
    'container.build_id' => '55e614c5',
    'container.build_time' => 1622455613,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHdrHasl');
